apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
  labels:
    app: nginx-demo
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command: ["sleep", "infinity"]
    ports: 
    - containerPort: 80
