apiVersion: v1
kind: Pod
metadata:
  name: my-app2
spec:
  containers:
    - name: my-container
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: my-storage
          mountPath: /usr/share/nginx/html
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: my-pvc
