#!/bin/bash

# Simple script to greet a user based on input parameters

echo "Script name: $0"
echo "First parameter: $1"
echo "Second parameter: $2"
echo "Number of parameters: $#"
echo "All parameters as a list: $@"
echo "All parameters as a single string: $*"

echo ""

if [ $# -lt 2 ]; then
  echo "Usage: $0 <first_name> <last_name>"
  exit 1
fi

first_name=$1
last_name=$2

echo "Hello, $first_name $last_name!"

