#!/bin/bash

# Перевірка кількості аргументів
if [ "$#" -ne 2 ]; then
  echo "Використання: $0 </home/pavlo/bash/HW5/copy_file> </home/pavlo/bash/copy_file>"
  exit 1
fi

SOURCE=$1
DESTINATION=$2

# Перевірка існування джерела
if [ ! -f "$SOURCE" ]; then
  echo "Помилка: Файл $SOURCE не існує."
  exit 1
fi

# Копіювання файлу
cp "$SOURCE" "$DESTINATION"

# Перевірка успішності операції
if [ "$?" -eq 0 ]; then
  echo "Файл успішно скопійовано з $SOURCE до $DESTINATION."
else
  echo "Помилка під час копіювання файлу."
  exit 1
fi
