apiVersion: v1
kind: Pod
metadata:
  name: api-checker
spec:
  serviceAccountName: api-reader
  containers:
  - name: curl
    image: curlimages/curl
    command: ["sh", "-c"]
    args:
    - >
      echo "=== Testing access ===";
      curl -sSk -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
      https://kubernetes.default.svc/api/v1/pods | head -n 20;
      echo "=== Done ===";
