apiVersion: v1
kind: Pod
metadata:
  name: secret-reader-v2
spec:
  serviceAccountName: vault-reader-sa
  containers:
  - name: reader
    image: ubuntu:latest # Використовуємо образ з доступом до apt
    command: ["/bin/bash", "-c"]
    args:
    - |
      # 1. Встановлення необхідних інструментів
      apt-get update && apt-get install -y curl jq wget unzip
      wget -q https://releases.hashicorp.com/vault/1.16.0/vault_1.16.0_linux_amd64.zip
      unzip vault_1.16.0_linux_amd64.zip
      mv vault /usr/local/bin/

      # 2. Встановлення змінних
      VAULT_ADDR="http://vault:8200"
      ROLE_NAME="webapp-role"
      
      echo "--- Спроба автентифікації ---"
      
      # 3. Отримання токена JWT Pod'а
      SA_JWT_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
      
      # 4. Автентифікація у Vault через Kubernetes Auth Method
      AUTH_RESPONSE=$(vault write -format=json auth/kubernetes/login role=$ROLE_NAME jwt=$SA_JWT_TOKEN)
      
      # 5. Перевірка на помилку автентифікації
      if echo \$AUTH_RESPONSE | grep -q "errors"; then
          echo "Помилка автентифікації! Дивіться JSON нижче:"
          echo \$AUTH_RESPONSE
          exit 1
      fi

      # 6. Вилучення токена клієнта Vault
      VAULT_CLIENT_TOKEN=$(echo \$AUTH_RESPONSE | jq -r '.auth.client_token')
      
      # 7. Встановлення токена клієнта та читання секрету
      export VAULT_TOKEN=\$VAULT_CLIENT_TOKEN
      echo "--- Секрет із Vault ---"
      vault kv get secret/webapp/config
      echo "--- Автентифікація успішна ---"
      sleep 3600
    env:
    - name: VAULT_ADDR
      value: "http://vault:8200" # Використовуємо ім'я сервісу 'vault'
