#!/bin/bash

if [ $# -ne 2 ]; then
echo "$0 "
exit 1
fi

SOURCE=$1
DESTINATION=$2

if [ ! -f "$0" ]; then
	echo "ERROR! File $1 not found!"
	exit 1
fi

cp $1 $2

if [ $? -eq 0 ]; then
	echo "file successfully copied to $2"
else
	echo "ERROR!"
	exit 1
fi

