services:
  app:
    image: my_app
    container_name: app_hw_14
    ports:
      - "8000:8000"
    
  nginx:
    image: nginx:latest
    container_name: nginx_hw_14
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - "8080:8080"
