version: "3.8"
services:
  jenkins-server:
    build:
      context: .
      dockerfile: Dockerfile.jenkins-server
    container_name: jenkins-server
    ports:
      - "8888:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  jenkins-agent:
    build:
      context: .
      dockerfile: Dockerfile.jenkins-agent
    container_name: jenkins-agent
    depends_on:
      - jenkins-server
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=/var/jenkins_home/.ssh/agent.id_rsa.pub
      - JENKINS_URL=http://jenkins-server:8080
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
