services:
  jenkins-server:
    build:
      context: .
      dockerfile: Dockerfile.jenkins-server
    container_name: jenkins-server
    ports:
      - "8888:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  jenkins-agent:
    build:
      context: .
      dockerfile: Dockerfile.jenkins-agent
    container_name: jenkins-agent
    depends_on:
      - jenkins-server
    environment:
      - JENKINS_URL=http://jenkins-server:8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      -url http://jenkins-server:8080
      -secret cb6b0be19dc7466d7581f1090120fd9c8f91e951bc0b7068fe51e75976590c6e
      -name jenkins-agent
      -workDir /home/jenkins/agent

volumes:
  jenkins_home:

