services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile.jenkins-master
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  jenkins-agent:
    build:
      context: .
      dockerfile: Dockerfile.jenkins-agent
    container_name: jenkins-agent
    depends_on:
      - jenkins-master
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=/var/jenkins_home/.ssh/agent.id_rsa.pub
      - JENKINS_URL=http://jenkins-master:8080
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
