pipeline {
  agent { label 'jenkins-agent' }

  environment {
    DOCKER_CREDENTIALS = 'dockerhub-credentials'
    IMAGE_NAME = 'savanchukpavlo/step_2'
    REPO_DIR = 'homeworks/step_2/for_step2'
  }

  stages {
    stage('Checkout') {
      steps {
        dir("${env.REPO_DIR}") {
          git url: 'https://github.com/Pavlo-1992/devops_9_pavlo.git', branch: 'main'
        }
      }
    }

    stage('Build Docker image') {
      steps {
        dir("${env.REPO_DIR}") {
          script {
                  sh "docker build -t $IMAGE_NAME:$BUILD_NUMBER ."

          }
        }
      }
    }

    stage('Run tests') {
      steps {
        dir("${env.REPO_DIR}") {
          script {
            try {
             sh "docker run --rm --name step2_test_container $IMAGE_NAME:$BUILD_NUMBER npm test"
             } catch (err) {
              echo 'Test failed!'
              error("Stop pipeline.")
            }
          }
        }
      }
    }

    stage('Push to Docker Hub') {
      when {
        expression { currentBuild.result == null || currentBuild.result == 'SUCCESS' }
      }
      steps {
        withCredentials([usernamePassword(
          credentialsId: "${env.DOCKER_CREDENTIALS}",
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          script {
            def imageTag = "${env.IMAGE_NAME}:${env.BUILD_NUMBER}"
            def latestTag = "${env.IMAGE_NAME}:latest"
            sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
            sh "docker tag ${imageTag} ${latestTag}"
            sh "docker push ${latestTag}"
          }
        }
      }
    }
  }
}
